name: ubuntu-package-status
version: '0.0.1'
summary: Fetch package version data for specified packages in the Ubuntu archive
description: |
  Helpful utility to fetch package version data for specified packages in the Ubuntu archive.

  Usage:

  ubuntu-package-status --help # to see all available options

grade: stable
confinement: strict

apps:
  ubuntu-package-status:
    command: wrapper
    plugs:
      - network
      - desktop
      - home

parts:
  ubuntu-package-status-wrapper:
    plugin: dump
    source: snap/local
    prepare: |
      chmod +x wrapper
    stage:
      - usr/bin/wrapper
    organize:
      wrapper: usr/bin/wrapper

  ubuntu-package-status:
    plugin: python
    python-version: python3
    requirements: requirements.txt
    source: .
    stage-packages:
      - python3-launchpadlib
