name: ubuntu-package-status
version: '0.0.1'
base: core20
summary: Fetch package version data for specified packages in the Ubuntu archive
description: |
  Helpful utility to fetch package version data for specified packages in the Ubuntu archive.

  Usage:

  ubuntu-package-status --help # to see all available options

grade: stable
confinement: strict

apps:
  ubuntu-package-status:
    environment:
      PATH: "$SNAP/usr/bin:$SNAP/bin/:$PATH"
      LC_ALL: "C.UTF-8"
    command: usr/bin/wrapper
    plugs:
      - network
      - home

parts:
  ubuntu-package-status-wrapper:
    plugin: dump
    source: snap/local
    override-build: |
      chmod +x wrapper
      snapcraftctl build
    organize:
      wrapper: usr/bin/wrapper
    stage:
      - usr/bin/wrapper

  ubuntu-package-status:
    plugin: python
    requirements:
      - src/requirements.txt
    source: .
    stage-packages:
      - python3-launchpadlib
